auditd_enable: true

auditd_max_log_file: 100
auditd_max_log_file_action: rotate
auditd_space_left_action: email
auditd_admin_space_left_action: halt
auditd_disk_full_action: halt
auditd_disk_error_action: halt
