ssh_port: 22
ssh_permit_root_login: "no"
ssh_password_authentication: "no"
ssh_pubkey_authentication: "yes"
ssh_permit_empty_passwords: "no"
ssh_challenge_response_authentication: "no"
ssh_use_pam: "yes"

ssh_client_alive_interval: 300
ssh_client_alive_count_max: 2
ssh_login_grace_time: 30
ssh_max_auth_tries: 3
ssh_max_sessions: 2

ssh_allow_groups: "{{ ssh_allowed_groups | default([]) }}"
