security_domain: dev

enable_selinux: true
enable_audit: true
enable_firewall: true
enable_gpu: false
enable_kubernetes: true
enable_container_runtime_hardening: true

ssh_allowed_groups:
  - devops

firewall_default_policy: deny

audit_log_retention_days: 14
